<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SecuroAPI_TestRunnerService-4316e85f-5927-4dd2-8610-f6574b12f2f1</UserSecretsId>
    <RootNamespace>SecuroAPI_TestRunnerService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Docker.DotNet.Enhanced" Version="4.3.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SecuroAPI.Contracts\SecuroAPI.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\.dockerignore">
      <Link>.dockerignore</Link>
      <DependentUpon>Dockerfile</DependentUpon>
    </Content>
  </ItemGroup>
</Project>
