<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\SecuroAPI.Contracts\SecuroAPI.Contracts.csproj" />
      <ProjectReference Include="..\SecuroAPI.DataAccess\SecuroAPI.DataAccess.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.7" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.7" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DTO's\AdminActions\" />
    </ItemGroup>

</Project>
